title: "testag"
description: "Site web pour tester GTM et GA4 dans le tracking"
baseurl: "/testag" 
url: "https://mnassrib.github.io" 
theme: jekyll-theme-cayman  # Thème à utiliser (optionnel, choisissez un thème qui vous convient)
include:
  - _layouts
  - assets

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
